#!/bin/sh

cap=$(cat /sys/class/power_supply/BAT0/capacity)
stat=$(cat /sys/class/power_supply/BAT0/status)
powersave=false
cap_group=$((cap/10))
icon=""



case $cap_group in 
	10)
		;;
	9)
		icon=""
		;;
	8)	icon=""
		;;
	7)	icon=""
		;;
	6)	icon=""
		;;
	5)	icon=""
		;;
	4)	icon=""
		;;
	3)	icon=""
		;;
	2)	icon="";
		powersave=true
		;;
	*)
		icon="";
		powersave=true
		;;
esac

brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

max=$(cat /sys/class/backlight/intel_backlight/max_brightness)

percentage=$(( (brightness*100)/max))

if [ "$stat" = "Charging" ]; then
	powersave=false
	icon=""

	if [[ "$percentage" -le 20 ]]; then
		acpi_bright -d intel_backlight -s 80%
	fi
fi

if [ "$powersave" = true ]; then 
	if [[ "$percentage" -gt 20 ]]; then 
		acpi_bright -d intel_backlight -s 20%
	fi
fi

echo "${icon} ${cap}%"
