#!/bin/sh

# Prints the current volume or 🔇 if muted.

vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

# If muted, print 婢and exit.
[ "$vol" != "${vol%\[MUTED\]}" ] && echo 婢 && exit

vol="${vol#Volume: }"
split() {
	# For ommiting the . without calling and external program.
	IFS=$2
	set -- $1
	printf '%s' "$@"
}
vol="$(split "$vol" ".")"
vol="${vol##0}"

case 1 in
	$((vol >= 70)) ) icon=" " ;;
	$((vol >= 30)) ) icon="墳 " ;;
	$((vol >= 1)) ) icon=" " ;;
	* ) echo "婢 " && exit ;;
esac

echo "$icon$vol%"
